// app/portal/components/Header.vue
<script setup lang="ts">
import Cookies from "js-cookie";

const walletAddress = useState<string | null>(
  "headerWalletAddress",
  () => null
);
const displayWalletBtn = useState<boolean>("displayWalletBtn", () => false);

const route = useRoute();

// FIXME: this is not gud, do better, just for MVP
// show wallet button on: examiner, soaps, index
// else dont
watch(route, (to, from) => {
  if (
    to.name?.toString() == "examiner" ||
    to.name?.toString() == "soaps" ||
    to.name?.toString() == "index"
  ) {
    displayWalletBtn.value = true;
  } else {
    displayWalletBtn.value = false;
  }
});

onMounted(() => {
  if (!walletAddress.value) {
    if (Cookies.get("walletAddress")) {
      walletAddress.value = Cookies.get("walletAddress")!;
    } else {
      return;
    }
  }
});
</script>

<template>
  <div class="lg:max-w-6xl m-auto">
    <header class="flex my-4 mx-4 lg:mx-0 justify-between">
      <NuxtLink href="/">
        <h1 class="text-6xl font-phenomenaBlack h-12 leading-6 cursor-pointer">
          soap
        </h1>
      </NuxtLink>
      <div v-if="displayWalletBtn" class="font-neueHaasUnicaRegular">
        <NuxtLink href="/mobile">
          <button
            class="bg-white hover:drop-shadow-md text-black font-bold py-2 w-40 rounded h-12 lg:invisible"
          >
            {{
              walletAddress
                ? `🔗 ${walletAddress.slice(0, 4)}...${walletAddress.slice(-4)}`
                : "WALLET"
            }}
          </button>
        </NuxtLink>
      </div>
    </header>
  </div>
</template>

// components/Header.tsx
import Link from 'next/link'
import { useEffect, useState } from "react";
import Cookies from "js-cookie";
import { useRouter } from 'next/router'
import styles from './Header.module.css'

export default function Header() {
    const [walletAddress, setWalletAddress] = useState<string | null>(null)
    let displayWalletBtn = false

    const router = useRouter()
    const pathName = router.pathname

    // FIXME: this is not gud, do better, just for MVP
    if (pathName.includes("dealer") || pathName.includes("mintooor") || pathName.includes("link")) {
        displayWalletBtn = false
    } else if (pathName.includes("examiner") || pathName.includes("soaps") || pathName === "/") {
        displayWalletBtn = true
    }

    useEffect(() => {

        if (!walletAddress) {
            if (Cookies.get('walletAddress')) {
                setWalletAddress(Cookies.get('walletAddress'))
            } else {
                return
            }
        }
    }, [])

    return (
        <>
            <div className="lg:max-w-6xl m-auto">
                <header className={`flex my-4 mx-4 lg:mx-0 justify-between ${styles.header}`}>
                    <Link href="/">
                        <h1 className={`${styles.soap} text-6xl font-phenomenaBlack h-12 leading-6 cursor-pointer`}>soap</h1>
                    </Link>
                    {displayWalletBtn && (
                        <div className="font-neueHaasUnicaRegular">
                            <Link href="/mobile">
                                <button className="bg-white hover:drop-shadow-md text-black font-bold py-2 w-40 rounded h-12 lg:invisible">
                                    {walletAddress ? `🔗 ${walletAddress.slice(0, 4)}...${walletAddress.slice(-4)}` : "WALLET"}
                                </button>
                            </Link>
                        </div>
                    )}
                </header>
            </div>
        </>
    )

}
